cleanup

diff --git a/distrom b/distrom
--- a/distrom
+++ b/distrom
@@ -1,7 +1,6 @@
 #!/usr/bin/env bash
 
-set -e
-set -o pipefail
+set -e -u -o pipefail
 
 # development environment
 #nix develop
@@ -35,8 +34,8 @@ $RUNAS modprobe nbd max_parts=8
 SECONDS=0
 TOTALTIME=0
 
-$RUNAS rm vyasa.qcow2 rootfs disk bash-5.2.37 coreutils-9.6 glibc-2.41 linux ncurses-6.5 util-linux-2.40.4 iproute2-6.13.0 elfutils-0.192 openssl-3.4.1 wget-1.25.0 libcap-2.75 zlib-1.3.1 zstd-1.5.7 musl-1.2.5 toybox-0.8.12 -rfd
-#$RUNAS rm vyasa.qcow2 rootfs disk toolchains bash-5.2.37 coreutils-9.6 glibc-2.41 linux ncurses-6.5 util-linux-2.40.4 iproute2-6.13.0 elfutils-0.192 openssl-3.4.1 wget-1.25.0 libcap-2.75 zlib-1.3.1 zstd-1.5.7 musl-1.2.5 toybox-0.8.12 -rfd
+$RUNAS rm vyasa.qcow2 rootfs disk binutils-2.44 bash-5.2.37 coreutils-9.6 glibc-2.41 linux ncurses-6.5 util-linux-2.40.4 iproute2-6.13.0 elfutils-0.192 openssl-3.4.1 wget-1.25.0 libcap-2.75 zlib-1.3.1 zstd-1.5.7 musl-1.2.5 toybox-0.8.12 -rfd
+#$RUNAS rm vyasa.qcow2 rootfs disk binutils-2.44 toolchains bash-5.2.37 coreutils-9.6 glibc-2.41 linux ncurses-6.5 util-linux-2.40.4 iproute2-6.13.0 elfutils-0.192 openssl-3.4.1 wget-1.25.0 libcap-2.75 zlib-1.3.1 zstd-1.5.7 musl-1.2.5 toybox-0.8.12 -rfd
 
 export WS=$(pwd)
 export VYASA=$(pwd)/rootfs
@@ -67,7 +66,7 @@ MAKE=$(which make)
 mkdir -p "$VYASA"/{boot,dev,etc/rc,home,mnt,proc,root,sys,tmp/run,usr/{bin,sbin,lib},var/run} &&
 chmod a+rwxt "$VYASA"/tmp && ln -s usr/{bin,sbin,lib} tmp/run "$VYASA"
 # DEBUG:
-cp /tmp/nxjs/{ash,bash,dash,fish,micro,nu,ping} $VYASA/bin/
+cp /tmp/nxjs/{ash,bash,dash,fish,neovim,nu,ping} $VYASA/bin/
 
 # init
 $RUNAS tee -a "$VYASA"/sbin/init > /dev/null << 'EOF' &&
@@ -87,6 +86,10 @@ ip route add 10.0.2.2 dev eth0
 ip route add 0/0 via 10.0.2.2 dev eth0
 
 dnsmasq -uroot
+
+#exec 0</dev/console
+#exec 1>/dev/console
+#exec 2>/dev/console
 
 #mknod -m 622 /dev/console c 5 1
 #mknod -m 666 /dev/null c 1 3
@@ -181,6 +184,24 @@ SECONDS=0
 
 #export HOST=x86_64-linux-gnu #overwriting to host
 export HOST=x86_64-linux-musl #overwriting to host
+export SYSROOT=$($CC --print-sysroot)
+
+## binutils-2.44
+#tar -xf binutils-2.44.tar.xz
+#mkdir binutils-2.44/build -p
+#cd binutils-2.44/build
+#../configure --host $HOST --prefix=/usr
+#
+#make -j16
+#make DESTDIR=$VYASA install
+##CFLAGS="-U_FORTIFY_SOURCE -O2 -fno-stack-protector" make -j16
+#cd $WS
+#
+#duration=$SECONDS
+#echo -e "\e[1;33mbinutils compile took: $((duration / 60)) minutes and $((duration % 60)) seconds elapsed.\e[0m"
+#TOTALTIME=$((TOTALTIME + duration))
+#SECONDS=0
+
 
 # Kernel
 tar -xf linux-6.13.5.tar.zst
@@ -285,7 +306,7 @@ SECONDS=0
 #tar -xf glibc-2.41.tar.xz
 #mkdir glibc-2.41/build -p
 #cd glibc-2.41/build
-#../configure --host $HOST --disable-werror --libdir=/lib --prefix=/usr
+#../configure --host $HOST --disable-werror libc_cv_forced_unwind=yes libc_cv_c_cleanup=yes --libdir=/lib --prefix=/usr
 #
 #make -j16
 #make DESTDIR=$VYASA install
@@ -494,6 +515,9 @@ SECONDS=0
 
 # LD
 echo -e "\e[1;32m$($VYASA/lib/libc.so $VYASA/usr/bin/uname -a)\e[0m"
+#ldconfig /usr/local/lib64/
+#openssl version -a
+#echo "/lib:/usr/local/lib:/usr/lib" > /etc/ld-musl-x86_64.path
 
 #$VYASA/bin/ld --help # check
 #$VYASA/bin/ld.so --help # check
@@ -539,10 +563,9 @@ $RUNAS grub-install --target=i386-pc --root-directory=$WS/disk --no-floppy --mod
 $RUNAS tee -a $WS/disk/boot/grub/grub.cfg > /dev/null <<EOF
 menuentry 'Vyasa' {
     set root='(hd0,1)'
-    linux /boot/vyasa root=/dev/sda1 rw 
+    linux /boot/vyasa root=/dev/sda1 rw console=tty0 console=ttyS0
 }
 EOF
-#console=ttyS0
 
 sync
 sync
